# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\hanning\Desktop\光电产品数据分析\Data_Processing_Software\data_merge\data_merge.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(468, 220)
        MainWindow.setMaximumSize(QtCore.QSize(700, 500))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.init_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.init_pushButton.setObjectName("init_pushButton")
        self.verticalLayout.addWidget(self.init_pushButton)
        self.merge_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.merge_pushButton.setObjectName("merge_pushButton")
        self.verticalLayout.addWidget(self.merge_pushButton)
        self.stop_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.stop_pushButton.setObjectName("stop_pushButton")
        self.verticalLayout.addWidget(self.stop_pushButton)
        self.close_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.close_pushButton.setObjectName("close_pushButton")
        self.verticalLayout.addWidget(self.close_pushButton)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.title_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")
        self.verticalLayout_2.addWidget(self.title_label)
        self.news_textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.news_textBrowser.setObjectName("news_textBrowser")
        self.verticalLayout_2.addWidget(self.news_textBrowser)
        self.progressBar_1 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_1.setProperty("value", 0)
        self.progressBar_1.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_1.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_1.setObjectName("progressBar_1")
        self.verticalLayout_2.addWidget(self.progressBar_1)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 468, 22))
        self.menubar.setObjectName("menubar")
        self.folder_menu = QtWidgets.QMenu(self.menubar)
        self.folder_menu.setObjectName("folder_menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.BP_merge_folder_action = QtWidgets.QAction(MainWindow)
        self.BP_merge_folder_action.setObjectName("BP_merge_folder_action")
        self.TG_merge_folder_action = QtWidgets.QAction(MainWindow)
        self.TG_merge_folder_action.setObjectName("TG_merge_folder_action")
        self.folder_menu.addAction(self.BP_merge_folder_action)
        self.folder_menu.addAction(self.TG_merge_folder_action)
        self.menubar.addAction(self.folder_menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.init_pushButton.setText(_translate("MainWindow", "初始化"))
        self.merge_pushButton.setText(_translate("MainWindow", "自动合并"))
        self.stop_pushButton.setText(_translate("MainWindow", "暂停"))
        self.close_pushButton.setText(_translate("MainWindow", "退出"))
        self.title_label.setText(_translate("MainWindow", "测试数据合并(FT+RT)"))
        self.folder_menu.setTitle(_translate("MainWindow", "文件夹"))
        self.BP_merge_folder_action.setText(_translate("MainWindow", "BP_merge_folder"))
        self.TG_merge_folder_action.setText(_translate("MainWindow", "TG_merge_folder"))
